# scheme3_pair_level.yaml

experiment_name: groupkfold_fold0_local_pair

seed: 42
device: cuda

data:
  train_csv: /data5/chensx/MyProject/chromosome_abnormality_new/data_cv/group_kfold_pair/fold_0/train_pair.csv
  val_csv: /data5/chensx/MyProject/chromosome_abnormality_new/data_cv/group_kfold_pair/fold_0/val_pair.csv
  test_csv: /data5/chensx/MyProject/chromosome_abnormality_new/data_cv/group_kfold_pair/fold_0/test_pair.csv
  image_size: 300
  num_workers: 4

model:
  name: resnet18
  num_classes: 2
  pretrained: true
  use_chromosome_id: false
  use_pair_input: true
  chr_embed_dim: 16

train:
  batch_size: 128
  epochs: 60
  lr: 0.0001
  weight_decay: 0.0001


loss:
  name: ce
  class_weights: null # [1.0, 20.0] null
  focal_gamma: 2.0

optimizer:
  name: adamw
  lr: 1e-4
  weight_decay: 1e-5

scheduler:
  name: cosine

output:
  save_dir: /data5/chensx/MyProject/chromosome_abnormality_new/outputs/experimentsromosome_abnormality_new/outputs/experiments