experiment_name: p2_pair_case_isolated_v1_local_global_resnet18_chrid_weighted_ce

seed: 42
device: cuda

data:
  train_csv: data_protocol/p1_pair_case_isolated_v1/train.csv
  val_csv: data_protocol/p1_pair_case_isolated_v1/val.csv
  test_csv: data_protocol/p1_pair_case_isolated_v1/test.csv
  image_size: 300
  num_workers: 4

model:
  name: resnet18
  num_classes: 2
  pretrained: true
  use_chromosome_id: true
  use_pair_input: true
  pair_model_type: local_global
  chr_embed_dim: 16
  use_pair_mixstyle: false
  mixstyle_p: 0.5
  mixstyle_alpha: 0.1

train:
  batch_size: 32
  epochs: 40
  lr: 0.0001
  weight_decay: 0.0001

loss:
  name: ce
  class_weights: [0.5208, 12.5305]
  focal_gamma: 2.0

output:
  save_dir: outputs/experiments

best_model_metric: auprc
